analyzer:
  errors:
    use_build_context_synchronously: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    use_build_context_synchronously: true
    avoid_print: true
    prefer_single_quotes: true
