name: enrollease_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  popover: ^0.3.1
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  delightful_toast: ^1.1.0
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  go_router: ^14.6.1
  appwrite: ^13.0.0
  table_calendar: ^3.1.2
  mime: ^2.0.0
  file_picker: ^8.1.4
  syncfusion_flutter_pdfviewer: ^27.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/svg/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Inknut Antiqua
      fonts:
        - asset: fonts/inknut_antiqua/InknutAntiqua-Black.ttf
        - asset: fonts/inknut_antiqua/InknutAntiqua-Regular.ttf
    #         style: italic
    - family: Macondo
      fonts:
        - asset: fonts/Macondo/Macondo-Regular.ttf

    - family: Lusitana
      fonts:
        - asset: fonts/Lusitana/Lusitana-Regular.ttf
        - asset: fonts/Lusitana/Lusitana-Bold.ttf

    - family: Ma Shan Zheng
      fonts:
        - asset: fonts/Ma_Shan_Zheng/MaShanZheng-Regular.ttf
